name: Esplanade News 
 
on:
  schedule:
    - cron: "*/5 * * * *" # Every 5 mins
 
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install -r requirements.txt
      - name: Scrape information
        run: python main.py
      - name: Commit database dumps
        run: |
          git config --global user.name ${{secrets.USER_NAME}}
          git config --global user.email ${{secrets.USER_EMAIL}}
          git add .
          git commit -m "Automated database dump"
          git push

    
  