name: run main.py
 
on:
  schedule:
    - cron: "0 */1 * * *" # Every hour
 
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: exeucte py script
        run: python main.py
        
      - name: commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git diff-index --quiet HEAD || (git commit -a -m "updated database" --allow-empty)
          
      - name: push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main 
    
